version: '3.3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    networks:
      - ms_network
    restart: always
    ports:
      - '5432:5432'

volumes:
  postgres_volume:
  media_volume:


networks:
  ms_network: